function info = student_info()
%STUDENT_INFO 학생 정보 — 채점 시 매칭에 사용.

    info.student_id   = '202127086';
    info.name         = '노민종';
    info.team_members = {};

    info.course = '자동제어 - 2026 봄';

    info.ai_usage = [ ...
        'ChatGPT used for controller architecture review, PID gain tuning ' ...
        'suggestions, MATLAB debugging, simulation result interpretation, ' ...
        'and report organization. Final controller parameters and results ' ...
        'were verified by the student using MATLAB simulations.' ...
    ];

    %% 검증
    if isempty(info.student_id) || ...
            contains(info.student_id, 'YOUR') || ...
            contains(info.student_id, '학번')
        warning('[student_info] 학번이 기입되지 않았습니다 — 채점 시 감점 + 매칭 불가');
    end

    if isempty(info.name) || ...
            contains(info.name, 'YOUR') || ...
            contains(info.name, '이름')
        warning('[student_info] 이름이 기입되지 않았습니다');
    end
end